# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 18:07
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('building_name', models.CharField(blank=True, max_length=200)),
                ('building_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('room_name', models.CharField(blank=True, max_length=200)),
                ('room_max_capacity', models.IntegerField()),
                ('building_floor', models.CharField(max_length=100)),
                ('building', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='roomcounter.Building')),
            ],
        ),
        migrations.CreateModel(
            name='RoomOccupancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('occupancy', models.IntegerField(default=0)),
                ('archived', models.BooleanField(default=False)),
                ('date_archived', models.DateTimeField(null=True)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_occupancy', to='roomcounter.Room')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('sensor_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('active', models.BooleanField(default=True)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='roomcounter.Room')),
            ],
        ),
        migrations.CreateModel(
            name='SensorResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('count_up', models.IntegerField(default=0)),
                ('count_down', models.IntegerField(default=0)),
                ('sensor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensor_results', to='roomcounter.Sensor')),
            ],
        ),
    ]
